### ISSUE TITLE
Subtree is lost during tree construction

### ISSUE THREAD

**Issue by ivany4** [antlr/antlrcs#70] opened 2017-01-23 10:39 UTC
I have a rule like this
```
list options {
  backtrack=true;
}
  : (d=decl e=delim l=list) -> ^($d $e) $l
  | decl
```
and the input like
```
decl delim decl delim decl
```
The expected tree is: ```(decl delim) (decl delim) decl```, which works with Java-based Antlr 3.2 generator.
However, with this generator, the first two trees are flat, producing ```decl decl decl```. Furthermore, if ```decl``` is a subtree, the first two objects would contain only the root nodes, while the last ```decl``` would have a correct subtree.

My system is:
```
Mono JIT compiler version 4.6.1 (Stable 4.6.1.5/ef43c15 Wed Oct 12 09:05:00 UTC 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  x86
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen
```
the grammar is with following options:
```
options {
	language=CSharp3;
	output=AST;
	TokenLabelType=CommonToken;
}
```

**Comment by sharwell** [comment] 2017-01-23 14:23
The GitHub history for ANTLR 3 doesn't contain the original commit where this behavior was introduced, but I found a comment describing it in the reference Java runtime:
https://github.com/antlr/antlr3/blob/master/runtime/Java/src/main/java/org/antlr/runtime/tree/RewriteRuleSubtreeStream.java#L54-L56

There may also be a test covering this, but so far I wasn't able to find it.

I'm closing this as **external** for now. While it appears to be by design, you can file an issue for the reference Java implementation ([antlr/antlr3](https://github.com/antlr/antlr3)) if you'd like to see a change made.

**Closed by sharwell** 2017-01-23 14:23 UTC
