### ISSUE TITLE
Dynamically included templates dont accept multiple arguments

### ISSUE THREAD

**Issue by hisuwh** [antlr/antlrcs#83] opened 2017-10-02 09:20 UTC
The documentation describes these two ways of including a template (amongst others):
 - name: `<template(argument-list)>`
 - dynamic `<(expr)(argument-list)>`

Both of these are described as a taking an `argument-list` but there appears to be a bug in the C# port of StringTemplate such that the dynamic version doesn't accept a list of arguments, only a single argument.  If you try this you get the following exception:

```
'=' came as a complete surprise to me
Antlr4.StringTemplate.Compiler.TemplateException: Exception of type 'Antlr4.StringTemplate.Compiler.TemplateException' was thrown.
```

I have recreated this here: https://github.com/hisuwh/StringTemplate.BugReproduction

`StringTemplate 4.0.8`

**Comment by sharwell** [comment] 2017-10-02 11:53
The limitation here is actually due to the use of *named* arguments. This is a limitation of the reference Java version of StringTemplate 4 as well.

Duplicate of antlr/stringtemplate4#102.

**Closed by sharwell** 2017-10-02 11:53 UTC

**Comment by hisuwh** [comment] 2017-10-02 14:06
Ok thanks.  As mentioned in the reference issue the documentation could do with being more clear about this
